# Generated by Django 4.1.7 on 2023-05-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Addess',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Username',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='pi'),
        ),
    ]
